import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',

  groups: [
    { name: 'brand', title: 'Brand', default: true },
    { name: 'contact', title: 'Contact' },
    { name: 'social', title: 'Social Media' },
    { name: 'homepage', title: 'Homepage' },
    { name: 'seo', title: 'SEO Defaults' },
  ],

  fields: [
    // ── Brand ─────────────────────────────────────────────────────
    defineField({
      name: 'siteName',
      title: 'Site Name',
      type: 'string',
      group: 'brand',
      initialValue: 'RKS E-Bikes',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Site Tagline',
      type: 'string',
      group: 'brand',
      description: 'Short brand tagline used in hero and footers',
    }),
    defineField({
      name: 'logo',
      title: 'Logo (light bg)',
      type: 'image',
      group: 'brand',
      options: { hotspot: true },
      fields: [
        defineField({ name: 'alt', title: 'Alt Text', type: 'string', initialValue: 'RKS E-Bikes' }),
      ],
    }),
    defineField({
      name: 'logoDark',
      title: 'Logo (dark bg)',
      type: 'image',
      group: 'brand',
      options: { hotspot: true },
      description: 'Used in dark header/footer',
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon',
      type: 'image',
      group: 'brand',
      description: '32×32 or 64×64 PNG',
    }),

    // ── Contact ───────────────────────────────────────────────────
    defineField({
      name: 'address',
      title: 'Head Office Address',
      type: 'text',
      group: 'contact',
      rows: 3,
    }),
    defineField({
      name: 'phone',
      title: 'Phone Number',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'email',
      title: 'Email Address',
      type: 'email',
      group: 'contact',
    }),
    defineField({
      name: 'salesEmail',
      title: 'Sales Email',
      type: 'email',
      group: 'contact',
    }),
    defineField({
      name: 'tradeEmail',
      title: 'Trade / B2B Email',
      type: 'email',
      group: 'contact',
    }),
    defineField({
      name: 'partsEmail',
      title: 'Parts Team Email',
      type: 'email',
      group: 'contact',
      description: 'Receives parts availability / bulk order enquiries. Falls back to Sales Email if left empty.',
    }),
    defineField({
      name: 'teamNotificationEmail',
      title: 'General Team Notification Email',
      type: 'email',
      group: 'contact',
      description: 'Catch-all for newsletter signups and any enquiry type without a dedicated address above.',
    }),
    defineField({
      name: 'googleMapsUrl',
      title: 'Google Maps URL (Head Office)',
      type: 'url',
      group: 'contact',
    }),

    // ── Social ────────────────────────────────────────────────────
    defineField({
      name: 'socialLinks',
      title: 'Social Media Links',
      type: 'object',
      group: 'social',
      fields: [
        defineField({ name: 'facebook', title: 'Facebook', type: 'url' }),
        defineField({ name: 'instagram', title: 'Instagram', type: 'url' }),
        defineField({ name: 'youtube', title: 'YouTube', type: 'url' }),
        defineField({ name: 'twitter', title: 'Twitter / X', type: 'url' }),
        defineField({ name: 'tiktok', title: 'TikTok', type: 'url' }),
        defineField({ name: 'linkedin', title: 'LinkedIn', type: 'url' }),
      ],
    }),

    // ── Hero Foreground (Product) Images ─────────────────────────
    defineField({
      name: 'heroSlide1Fg',
      title: 'Hero Slide 1 — E-Bike Product Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 1 product image (shown on the right). PNG with transparent background works best. Replaces the 3D animation when uploaded. Recommended: 900×700px.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'heroSlide2Fg',
      title: 'Hero Slide 2 — E-Bike Product Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 2 product image (right side). Replaces the 3D animation when uploaded.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'heroSlide3Fg',
      title: 'Hero Slide 3 — E-Bike Product Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 3 product image (right side). Replaces the 3D animation when uploaded.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'heroSlide4Fg',
      title: 'Hero Slide 4 — E-Bike Product Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 4 product image (right side). Replaces the 3D animation when uploaded.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'heroSlide5Fg',
      title: 'Hero Slide 5 — E-Bike Product Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 5 product image (right side). Replaces the 3D animation when uploaded.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),

    // ── Homepage Background Images ────────────────────────────────
    defineField({
      name: 'heroSlide1Bg',
      title: 'Hero Slide 1 — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 1: "Power Redefined" — full-screen background. Recommended: 1920×1080px, landscape e-bike shot.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'heroSlide2Bg',
      title: 'Hero Slide 2 — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 2: "Crafted to Perfection" — full-screen background.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'heroSlide3Bg',
      title: 'Hero Slide 3 — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 3: "Find Your Perfect Ride" — full-screen background.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'heroSlide4Bg',
      title: 'Hero Slide 4 — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 4: "OEM E-Bike Parts" — full-screen background.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'heroSlide5Bg',
      title: 'Hero Slide 5 — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: 'Slide 5: "Become a Partner" — full-screen background.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'partsSectionBg',
      title: 'Parts Section — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: '"E-Bike Parts & Accessories" section background. Shown at low opacity behind the content.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'whySectionBg',
      title: 'Why Choose Us — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: '"Italian Soul. Global Performance." section background. Shown at very low opacity.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'b2bSectionBg',
      title: 'B2B / Trade Section — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: '"Are You a Dealer or Distributor?" banner background.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),
    defineField({
      name: 'dealerSectionBg',
      title: 'Dealer Section — Background Image',
      type: 'image',
      group: 'homepage',
      options: { hotspot: true },
      description: '"Find Your Nearest Dealer" map-side background image.',
      fields: [defineField({ name: 'alt', title: 'Alt Text', type: 'string' })],
    }),

    // ── Homepage ──────────────────────────────────────────────────
    defineField({
      name: 'statsBar',
      title: 'Homepage Stats Bar',
      type: 'array',
      group: 'homepage',
      description: 'Up to 4 stats shown in the animated bar below the hero',
      of: [
        {
          type: 'object',
          name: 'stat',
          fields: [
            defineField({ name: 'value', title: 'Value', type: 'string', description: 'e.g. "120+"', validation: (R) => R.required() }),
            defineField({ name: 'label', title: 'Label', type: 'string', description: 'e.g. "Countries Served"', validation: (R) => R.required() }),
          ],
          preview: {
            select: { title: 'value', subtitle: 'label' },
          },
        },
      ],
      validation: (R) => R.max(4),
    }),
    defineField({
      name: 'announcementBanner',
      title: 'Announcement Banner',
      type: 'string',
      group: 'homepage',
      description: 'Optional top-of-page banner message. Leave blank to hide.',
    }),
    defineField({
      name: 'footerText',
      title: 'Footer Copyright Text',
      type: 'string',
      group: 'homepage',
      description: 'Leave blank to use default "© {year} RKS S.r.l. All rights reserved."',
    }),

    // ── SEO Defaults ──────────────────────────────────────────────
    defineField({
      name: 'metaTitle',
      title: 'Default Meta Title',
      type: 'string',
      group: 'seo',
      validation: (R) => R.max(70),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Default Meta Description',
      type: 'text',
      group: 'seo',
      rows: 3,
      validation: (R) => R.max(160),
    }),
    defineField({
      name: 'ogImage',
      title: 'Default Open Graph Image',
      type: 'image',
      group: 'seo',
      options: { hotspot: true },
      description: 'Used when no page-specific OG image is set. 1200×630px recommended.',
    }),
    defineField({
      name: 'googleVerification',
      title: 'Google Search Console Verification',
      type: 'string',
      group: 'seo',
    }),
  ],

  preview: {
    select: {
      title: 'siteName',
      subtitle: 'tagline',
      media: 'logo',
    },
  },
})
